### ISSUE TITLE
`should_warn_when_session_count_exceeds_threshold` needs its connection limit increased

### ISSUE THREAD

**Issue by k0machi** [scylladb/scylla-java-driver-matrix#46] opened 2024-04-02 14:34 UTC
Same as #44, but for scylla-4.x branch, need to increase connection limit so that test can actually work.

Test: should_warn_when_session_count_exceeds_threshold
Class: 4.17.0.0.com.datastax.oss.driver.core.SessionLeakIT
 ```
appender.doAppend(<any>);
Never wanted here:
-> at com.datastax.oss.driver.core.SessionLeakIT.should_warn_when_session_count_exceeds_threshold(SessionLeakIT.java:88)
But invoked here:
-> at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
 (org.mockito.exceptions.verification.NeverWantedButInvoked)```

**Comment by dimakr** [comment] 2024-04-29 07:25
The issue doesn't seem to be similar to what was observed in #44.

1st, the test is not reproduced locally, but is constantly failing in Jenkins.
Here the test scenario is Simulacron based and the observed behavior is:
- the isolated test inits a logger for DefaultSession.class
- sets `advanced.session-leak.threshold` option to 4
- creates 4 test sessions (i.e. the session threshold should not be crossed yet) and checks that no logs were issued and captured

The last step fails as there is a warning log message captured, saying 
```
[main] WARN  c.d.o.d.i.c.session.DefaultSession - You have too many session instances: 5 active, expected less than 4 (see 'advanced.session-leak.threshold' in the configuration)
```
i.e. something creates a session after the logger was initialized, additionally to 4 test sessions that the test creates explicitly.

For now I tried to increase verbosity for some classes, but this didn't help to identify what creates the redundant session.
Need to increase logging verbosity for other parts, or all driver, to try to identify the root cause.

**Comment by dimakr** [comment] 2024-04-30 16:44
After investigation it turned out that there is PeersV2NodeRefreshIT#should_successfully_send_peers_v2_node_refresh_query test that creates a test session, but doesn't close it after the test itself is finished. This session later leaks into SessionLeakIT.

Below is how it looks like in logs (additional verbosity was enabled for debugging purposes, compared to standard logging config):
- PeersV2NodeRefreshIT#should_successfully_send_peers_v2_node_refresh_query test creates a test session s379, the logs say that there is 1 active session
- the test finishes without closing the session
- the subsequent SpeculativeExecutionIT test creates its own session s380, but the logs say that there are already 2 active sessions. This means that session s379 was not closed and leaked to subsequent tests
```
[2024-04-30T09:51:48.435Z] [INFO] Running com.datastax.oss.driver.core.PeersV2NodeRefreshIT
...
[2024-04-30T09:51:48.438Z] 09:51:48.204 [main] DEBUG c.d.o.d.i.c.session.DefaultSession - Creating new session s379 (1 live instances)
...
[2024-04-30T09:51:48.439Z] [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.081 s - in com.datastax.oss.driver.core.PeersV2NodeRefreshIT
[2024-04-30T09:51:48.439Z] [INFO] Running com.datastax.oss.driver.core.specex.SpeculativeExecutionIT
...
[2024-04-30T09:51:48.442Z] 09:51:48.287 [main] DEBUG c.d.o.d.i.c.session.DefaultSession - Creating new session s380 (2 live instances)
...
```

PR https://github.com/scylladb/scylla-java-driver-matrix/pull/49 fixes the described behaviour by adding After cleanuo method to PeersV2NodeRefreshIT test class, to properly close the test session.

**Closed** 2024-05-02 08:11 UTC
